apiVersion: v1
kind: Service
metadata:
  name: products-ra-products
  labels:
    helm.sh/chart: ra-products-0.1.1
    app.kubernetes.io/name: ra-products
    app.kubernetes.io/instance: products
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ra-products
    app.kubernetes.io/instance: products